Update apache.pp
Fixes the following error when provisioning VM's:
```
Error: Duplicate declaration: File[/var/www/accountingnow] is already declared in file /tmp/vagrant-puppet/modules-2623f1aee4ddcc04fb208aea00ed53cd/phish_me_website/manifests/install.pp:11; cannot redeclare at /tmp/vagrant-puppet/modules-2623f1aee4ddcc04fb208aea00ed53cd/apache/manifests/vhost.pp:272
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
Non-zero exit status...
Error provisioning VMs, destroying VMs and exiting SecGen.
```